### PR TITLE
home page screen

### PR DESCRIPTION
**Pull request by shristabaruah**
- home page screen
captures_chrome-capture-2022-3-27

### CODE REVIEW

**Review by Kevin-Solomon — CHANGES_REQUESTED** [review]
Can you make the images span the entire width of the card?
As it looks a bit odd with width of 50%

**Comment by shristabaruah** [comment]
> Can you make the images span the entire width of the card? As it looks a bit odd with width of 50%
yes, I have made the suggested changes @Kevin-Solomon

**Comment by shristabaruah** [comment]
> Can you make the images span the entire width of the card? As it looks a bit odd with width of 50%
yes, I have made the suggested changes @Kevin-Solomon

**Review by Kevin-Solomon — CHANGES_REQUESTED** [review]
image
Why is there white space? after listing videos.
Maybe it is because the height for listing video is ```auto```.
Also the first video card is not displaying properly.

**Comment by shristabaruah** [comment]
Thank you @Kevin-Solomon  for pointing it out . My screen is smaller in size so I couldn't figure it out. I have made the required changes can you check it now!

**Review by Kevin-Solomon — APPROVED** [review]
You can minimize the gap between two video cards.
Other than that it looks good.

**Review by gadgetfather — APPROVED** [review]

**Pull request merged**
